article_index:
    path:     /{page}
    defaults: 
        _controller: "DevToolsBlogBundle:Article:index"
        page : 1
    methods:  GET
    requirements:
        page: \d+
        
article_show:
    path:     /{id}/show
    defaults: { _controller: "DevToolsBlogBundle:Article:show" }
    methods:  [GET, POST]

article_new:
    path:     /new
    defaults: { _controller: "DevToolsBlogBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevToolsBlogBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /article/{id}/delete
    defaults: { _controller: "DevToolsBlogBundle:Article:delete" }
    methods:  DELETE

comment_delete:
    path:     /comment/{id}/delete
    defaults: { _controller: "DevToolsBlogBundle:Article:deletecom" }
    methods:  DELETE
    
article_myarticles:
    path:     /myarticles/{page}
    defaults: 
        _controller: "DevToolsBlogBundle:Article:myarticles"
        page: 1
    methods:  GET
    requirements:
        page: \d+